# Generated by Django 4.1.7 on 2023-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0003_alter_book_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_image_path",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
