# Generated by Django 4.1.7 on 2023-03-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0005_remove_book_book_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_author",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_price",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
